### ISSUE TITLE
GNOME 3.32 support

### ISSUE THREAD

**Issue by feimosi** [soal/gnome-shell-fullscreen-hot-corner#2]
After upgrading to GNOME 3.32, the extension fails with the following error:

```
TypeError: this._construct is not a function
```

**Comment by soal** [comment]
FIxed in the new version. Currently on review on GNOME extensions [website](https://extensions.gnome.org/extension/1562/fullscreen-hot-corner/)

**Comment by soal** [comment]
Already approved. That was fast)
